### ISSUE TITLE
Pretrained model download

### ISSUE THREAD

**Issue by Globolik** [tjpulkl/CDGNet#6]
Hi, I'm trying to access the LIP_epoch_149.pth, but I cannot download it from baidu link, can you please provide Google disc link.

**Comment by Globolik** [comment]
The reason why I ask to upload file from https://pan.baidu.com/s/1WyifPOOE0SqIzCje-d1kzA?pwd=81la to google, is because the same file on google disc is smaller (250MB) and it doesn't have all the weights. But file in the link is 300MB and it probably right one.

**Comment by kinivi** [comment]
@Globolik Indeed, the model on Baidu disk is working. Here is [GDrive link](https://drive.google.com/drive/folders/1E9GutnsqFzF16bC5_DmoSXFIHYuU547L?usp=sharing)


@tjpulkl Please, re-upload the saved weights. Thank you for maintaining reproducibility in the community.
